name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PowerShell
      uses: actions/setup-powershell@v1
      with:
        pwsh: true

    - name: Install PSScriptAnalyzer
      run: |
        Install-Module -Name PSScriptAnalyzer -Force -SkipPublisherCheck

    - name: Run PSScriptAnalyzer
      run: |
        $results = Invoke-ScriptAnalyzer -Path . -Recurse -Severity Error
        if ($results) {
          Write-Host "PSScriptAnalyzer found errors:"
          $results | Format-Table -AutoSize
          exit 1
        } else {
          Write-Host "No errors found by PSScriptAnalyzer."
        }

    - name: Validate script syntax
      run: |
        Get-ChildItem -Path . -Filter *.ps1 -Recurse | ForEach-Object {
          try {
            $null = [System.Management.Automation.PSParser]::Tokenize((Get-Content $_.FullName -Raw), [ref]$null)
            Write-Host "Syntax OK: $($_.FullName)"
          } catch {
            Write-Host "Syntax error in $($_.FullName): $($_.Exception.Message)"
            exit 1
          }
        }